- dwie klasy w dwóch plikach,
- klasy: route, runner
- maja zawierać funkcje getRunner(array) i getTime(float)
- ma zwrócić ID, Dystans, Czas, 
- kiedy zawodnikowi spadnie kondycja do 10 biegnie pozniej stala predkoscia
- zawodnicy moga sie zmieniac
- minimalna kondycja to 10
- kondycja spada co minute
- predkosc km/h zmienia sie wraz ze spadkiem kondycji